version: '3'

services:
  db:
    image: 'mysql/mysql-server:5.7'
    ports:
           - "3306:3306"
    environment:
           - MYSQL_ROOT_PASSWORD=1234
           - MYSQL_DATABASE=tpachato
           - MYSQL_USER=root
           - MYSQL_PASSWORD=
           - MYSQL_ROOT_HOST=%
    healthcheck:
           test: ["CMD","mysqladmin","ping","-h","localhost"]
           timeout: 20s
           retries: 10
    restart: always
  backendserver:
    image: 'nadatlili/spring:latest'
    ports:
           - "8081"
    links:
           - "db"
    depends_on:
           - "db"
    restart: always
  frontend:
    image: 'nadatlili/angular:latest'
    links:
           - "backendserver"
    depends_on:
           - "backendserver"
    ports:
           - "80:80"
