version: "3"

services:
  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/tpachato?useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    networks:
      - springmysql-net
    depends_on:
      - mysqldb
    restart: always

  mysqldb:
    container_name: 'mysqldb'
    image: "mysql:5.7"
    networks:
      - springmysql-net
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=tpachato
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_ROOT_HOST=%
    restart: always

networks:
  springmysql-net: